name: taylorStaff
version: 1.0
main: me.taylor.taylorStaff.taylorStaff
authors: [taylor]
commands:
    report:
           usage: /<command>
    helpop:
           usage: /<command>
           aliases: [request]
    freeze:
          usage: /<command>
          aliases: [ss]
    ban:
          usage: /<command>
    kick:
          usage: /<command>
permissions:
    moderation.freeze.freeze: {}
    moderation.request.recieve: {}
    moderation.report.recieve: {}
    moderation.kick.kick: {}
